### ISSUE TITLE
asyncio.exceptions.CancelledError

### ISSUE THREAD

**Issue by observer-user** [alpacahq/alpaca-backtrader-api#120]
Hey, I am trying to run multiple datas example (https://github.com/alpacahq/alpaca-backtrader-api/blob/master/sample/strategy_multiple_datas.py) using [alpaca-proxy-agent](https://github.com/shlomikushchi/alpaca-proxy-agent) project and I have the following error in IDE:

```
2020-10-07 16:36:52,693 code = 1000 (OK), no reason
Exception in thread Thread-7:
Traceback (most recent call last):
  File "\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()2020-10-07 16:36:52,708 connected to: wss://paper-api.alpaca.markets/stream

  File "\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)

  File "\BackTradeAlpacaMultipleData\venv\lib\site-packages\alpaca_backtrader_api\alpacastore.py", line 703, in _t_streaming_prices
    streamer.run()

  File "\BackTradeAlpacaMultipleData\venv\lib\site-packages\alpaca_backtrader_api\alpacastore.py", line 145, in run
    self.conn.run(channels)

  File "\BackTradeAlpacaMultipleData\venv\lib\site-packages\alpaca_trade_api\stream2.py", line 293, in run
    loop.run_until_complete(self.consume())

  File "\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()

asyncio.exceptions.CancelledError
```

Log from the Docker container:
```
alpaca-proxy_1  | < {'action': 'authenticate', 'data': {'key_id': '123', 'secret_key': '456'}}
alpaca-proxy_1  | < {'action': 'listen', 'data': {'streams': ['alpacadatav1/Q.AAPL']}}
alpaca-proxy_1  | < {'action': 'authenticate', 'data': {'key_id': '123', 'secret_key': '456'}}
alpaca-proxy_1  | < {'action': 'listen', 'data': {'streams': ['alpacadatav1/Q.GOOG']}}
alpaca-proxy_1  | 'NoneType' object has no attribute 'send'
alpaca-proxy_1  | Done
alpaca-proxy_1  | 2020-10-07 20:36:52,130 root connected to: wss://data.alpaca.markets/stream
```

If restart multiple datas example without stopping a proxy container, then I don't see errors anymore, but strategy never executes `next()`

Versions:
alpaca-backtrader-api-0.11.0
alpaca-trade-api-0.50.1
alpaca-proxy-agent-0.5.5

Running code on Windows 10

**Comment by shlomikushchi** [comment]
Hi, are you using the Alpaca data stream or the Polygon data stream?

**Comment by observer-user** [comment]
I am using Alpaca data stream

**Comment by observer-user** [comment]
@shlomikushchi, I am not sure if it helps, but here is the log with DEBUG level from IDE

```
2020-10-08 18:30:25,905 Starting new HTTPS connection (1): paper-api.alpaca.markets:443
2020-10-08 18:30:26,249 https://paper-api.alpaca.markets:443 "GET /v2/account HTTP/1.1" 200 677
2020-10-08 18:30:26,251 Using proactor: IocpProactor
2020-10-08 18:30:26,254 Using proactor: IocpProactor
Starting Portfolio Value: 100749.18
2020-10-08 18:30:26,317 https://paper-api.alpaca.markets:443 "GET /v2/account HTTP/1.1" 200 677
2020-10-08 18:30:26,388 https://paper-api.alpaca.markets:443 "GET /v2/positions HTTP/1.1" 200 2
2020-10-08 18:30:26,417 client - state = CONNECTING
2020-10-08 18:30:26,474 https://paper-api.alpaca.markets:443 "GET /v2/assets/AAPL HTTP/1.1" 200 225
2020-10-08 18:30:26,486 Using proactor: IocpProactor
2020-10-08 18:30:26,557 Using proactor: IocpProactor
2020-10-08 18:30:26,585 https://paper-api.alpaca.markets:443 "GET /v2/assets/GOOG HTTP/1.1" 200 237
2020-10-08 18:30:26,595 Using proactor: IocpProactor
2020-10-08 18:30:26,601 client - event = connection_made(<asyncio.sslproto._SSLProtocolTransport object at 0x0000021ED8593BE0>)
2020-10-08 18:30:26,612 client > GET /stream HTTP/1.1
2020-10-08 18:30:26,612 client > Headers([('Host', 'paper-api.alpaca.markets'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'websoket_key'), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.8 websockets/8.1')])
2020-10-08 18:30:26,645 Using proactor: IocpProactor
2020-10-08 18:30:26,661 client - event = data_received(<188 bytes>)
2020-10-08 18:30:26,662 client < HTTP/1.1 101 Switching Protocols
2020-10-08 18:30:26,662 client < Headers([('Server', 'nginx/1.16.1'), ('Date', 'Thu, 08 Oct 2020 22:30:24 GMT'), ('Connection', 'upgrade'), ('Upgrade', 'websocket'), ('Sec-WebSocket-Accept', 'key=')])
2020-10-08 18:30:26,662 client - state = OPEN
2020-10-08 18:30:26,662 client > Frame(fin=True, opcode=1, data=b'{"action": "authenticate", "data": {"key_id": "123", "secret_key": "456"}}', rsv1=False, rsv2=False, rsv3=False)
2020-10-08 18:30:26,676 client - state = CONNECTING
2020-10-08 18:30:26,677 client - event = connection_made(<_ProactorSocketTransport fd=836>)
2020-10-08 18:30:26,683 client > GET /stream HTTP/1.1
2020-10-08 18:30:26,683 client > Headers([('Host', 'localhost:8765'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'websoket_key'), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.8 websockets/8.1')])
2020-10-08 18:30:26,706 client - event = data_received(<247 bytes>)
2020-10-08 18:30:26,706 client < HTTP/1.1 101 Switching Protocols
2020-10-08 18:30:26,706 client < Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', 'n/key='), ('Sec-WebSocket-Extensions', 'permessage-deflate'), ('Date', 'Thu, 08 Oct 2020 22:30:26 GMT'), ('Server', 'Python/3.6 websockets/8.1')])
2020-10-08 18:30:26,707 client - state = OPEN
2020-10-08 18:30:26,707 client > Frame(fin=True, opcode=1, data=b'{"action": "authenticate", "data": {"key_id": "123", "secret_key": "456"}}', rsv1=False, rsv2=False, rsv3=False)
2020-10-08 18:30:26,740 client - event = data_received(<53 bytes>)
2020-10-08 18:30:26,756 client < Frame(fin=True, opcode=1, data=b'{"data": {"status": "authorized"}, "stream": "authorization"}', rsv1=False, rsv2=False, rsv3=False)
2020-10-08 18:30:26,756 connected to: ws://localhost:8765/stream
2020-10-08 18:30:26,757 client > Frame(fin=True, opcode=1, data=b'{"action": "listen", "data": {"streams": ["alpacadatav1/Q.AAPL"]}}', rsv1=False, rsv2=False, rsv3=False)
2020-10-08 18:30:26,768 client - state = CONNECTING
2020-10-08 18:30:26,781 client - event = connection_made(<_ProactorSocketTransport fd=2120>)
2020-10-08 18:30:26,787 client > GET /stream HTTP/1.1
2020-10-08 18:30:26,787 client > Headers([('Host', 'localhost:8765'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'websoket_key'), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.8 websockets/8.1')])
2020-10-08 18:30:26,787 client - event = data_received(<83 bytes>)
2020-10-08 18:30:26,787 client < Frame(fin=True, opcode=2, data=b'{"stream":"authorization","data":{"action":"authenticate","status":"authorized"}}', rsv1=False, rsv2=False, rsv3=False)
2020-10-08 18:30:26,788 connected to: wss://paper-api.alpaca.markets/stream
2020-10-08 18:30:26,788 client > Frame(fin=True, opcode=1, data=b'{"action": "listen", "data": {"streams": ["trade_updates"]}}', rsv1=False, rsv2=False, rsv3=False)
2020-10-08 18:30:26,800 client - event = data_received(<247 bytes>)
2020-10-08 18:30:26,800 client < HTTP/1.1 101 Switching Protocols
2020-10-08 18:30:26,800 client < Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', 'tz/w/key='), ('Sec-WebSocket-Extensions', 'permessage-deflate'), ('Date', 'Thu, 08 Oct 2020 22:30:26 GMT'), ('Server', 'Python/3.6 websockets/8.1')])
2020-10-08 18:30:26,800 client - state = OPEN
2020-10-08 18:30:26,801 client > Frame(fin=True, opcode=1, data=b'{"action": "authenticate", "data": {"key_id": "123", "secret_key": "456"}}', rsv1=False, rsv2=False, rsv3=False)
2020-10-08 18:30:26,811 client - event = data_received(<53 bytes>)
2020-10-08 18:30:26,821 client < Frame(fin=True, opcode=1, data=b'{"data": {"status": "authorized"}, "stream": "authorization"}', rsv1=False, rsv2=False, rsv3=False)
2020-10-08 18:30:26,827 connected to: ws://localhost:8765/stream
2020-10-08 18:30:26,832 client > Frame(fin=True, opcode=1, data=b'{"action": "listen", "data": {"streams": ["alpacadatav1/Q.GOOG"]}}', rsv1=False, rsv2=False, rsv3=False)
2020-10-08 18:30:26,854 client - event = data_received(<4 bytes>)
2020-10-08 18:30:26,865 client < Frame(fin=True, opcode=8, data=b'\x03\xe8', rsv1=False, rsv2=False, rsv3=False)
2020-10-08 18:30:26,871 client - event = data_received(<61 bytes>)
2020-10-08 18:30:26,871 client - state = CLOSING
2020-10-08 18:30:26,881 client < Frame(fin=True, opcode=2, data=b'{"stream":"listening","data":{"streams":["trade_updates"]}}', rsv1=False, rsv2=False, rsv3=False)
2020-10-08 18:30:26,891 client > Frame(fin=True, opcode=8, data=b'\x03\xe8', rsv1=False, rsv2=False, rsv3=False)
2020-10-08 18:30:26,919 client - event = eof_received()
2020-10-08 18:30:26,919 client - event = connection_lost(None)
2020-10-08 18:30:26,919 client - state = CLOSED
2020-10-08 18:30:26,920 client x code = 1000, reason = [no reason]
2020-10-08 18:30:26,936 code = 1000 (OK), no reason
Exception in thread Thread-7:
Traceback (most recent call last):
  File "\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "\BackTradeAlpacaMultipleData\venv\lib\site-packages\alpaca_backtrader_api\alpacastore.py", line 703, in _t_streaming_prices
    streamer.run()
  File "\BackTradeAlpacaMultipleData\venv\lib\site-packages\alpaca_backtrader_api\alpacastore.py", line 145, in run
    self.conn.run(channels)
  File "\BackTradeAlpacaMultipleData\venv\lib\site-packages\alpaca_trade_api\stream2.py", line 293, in run
    loop.run_until_complete(self.consume())
  File "\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
```

**DEBUG level from alpaca-proxy-agent**

```
alpaca-proxy_1  | 2020-10-08 22:35:35,537 root Using the Alpaca Websocket
alpaca-proxy_1  | 2020-10-08 22:35:35,537 asyncio Using selector: EpollSelector
alpaca-proxy_1  | 2020-10-08 22:35:38,185 websockets.protocol server - state = CONNECTING
alpaca-proxy_1  | 2020-10-08 22:35:38,185 websockets.protocol server - event = connection_made(<_SelectorSocketTransport fd=7 read=idle write=<idle, bufsize=0>>)
alpaca-proxy_1  | 2020-10-08 22:35:38,194 websockets.protocol server - event = data_received(<268 bytes>)
alpaca-proxy_1  | 2020-10-08 22:35:38,194 websockets.server server < GET /stream HTTP/1.1
alpaca-proxy_1  | 2020-10-08 22:35:38,194 websockets.server server < Headers([('Host', 'localhost:8765'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'websoket_key), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.8 websockets/8.1')])
alpaca-proxy_1  | 2020-10-08 22:35:38,195 websockets.server server > HTTP/1.1 101 Switching Protocols
alpaca-proxy_1  | 2020-10-08 22:35:38,195 websockets.server server > Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', 'key='), ('Sec-WebSocket-Extensions', 'permessage-deflate'), ('Date', 'Thu, 08 Oct 2020 22:35:38 GMT'), ('Server', 'Python/3.6 websockets/8.1')])
alpaca-proxy_1  | 2020-10-08 22:35:38,196 websockets.protocol server - state = OPEN
alpaca-proxy_1  | 2020-10-08 22:35:38,210 websockets.protocol server - event = data_received(<128 bytes>)
alpaca-proxy_1  | 2020-10-08 22:35:38,211 websockets.protocol server < Frame(fin=True, opcode=1, data=b'{"action": "authenticate", "data": {"key_id": "123", "secret_key": "456"}}', rsv1=False, rsv2=False, rsv3=False)
alpaca-proxy_1  | < {'action': 'authenticate', 'data': {'key_id': '123', 'secret_key': '456'}}
alpaca-proxy_1  | 2020-10-08 22:35:38,211 websockets.protocol server > Frame(fin=True, opcode=1, data=b'{"data": {"status": "authorized"}, "stream": "authorization"}', rsv1=False, rsv2=False, rsv3=False)
alpaca-proxy_1  | 2020-10-08 22:35:38,221 websockets.protocol server - event = data_received(<51 bytes>)
alpaca-proxy_1  | 2020-10-08 22:35:38,222 websockets.protocol server < Frame(fin=True, opcode=1, data=b'{"action": "listen", "data": {"streams": ["alpacadatav1/Q.AAPL"]}}', rsv1=False, rsv2=False, rsv3=False)
alpaca-proxy_1  | < {'action': 'listen', 'data': {'streams': ['alpacadatav1/Q.AAPL']}}
alpaca-proxy_1  | <class 'RuntimeError'>
alpaca-proxy_1  | 2020-10-08 22:35:38,222 asyncio Using selector: EpollSelector
alpaca-proxy_1  | 2020-10-08 22:35:38,273 websockets.protocol server - state = CONNECTING
alpaca-proxy_1  | 2020-10-08 22:35:38,273 websockets.protocol server - event = connection_made(<_SelectorSocketTransport fd=12 read=idle write=<idle, bufsize=0>>)
alpaca-proxy_1  | 2020-10-08 22:35:38,294 websockets.protocol server - event = data_received(<268 bytes>)
alpaca-proxy_1  | 2020-10-08 22:35:38,295 websockets.server server < GET /stream HTTP/1.1
alpaca-proxy_1  | 2020-10-08 22:35:38,295 websockets.server server < Headers([('Host', 'localhost:8765'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'websoket_key'), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.8 websockets/8.1')])
alpaca-proxy_1  | 2020-10-08 22:35:38,295 websockets.server server > HTTP/1.1 101 Switching Protocols
alpaca-proxy_1  | 2020-10-08 22:35:38,295 websockets.server server > Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', 'key+zTrA3gnjVJ8='), ('Sec-WebSocket-Extensions', 'permessage-deflate'), ('Date', 'Thu, 08 Oct 2020 22:35:38 GMT'), ('Server', 'Python/3.6 websockets/8.1')])
alpaca-proxy_1  | 2020-10-08 22:35:38,296 websockets.protocol server - state = OPEN
alpaca-proxy_1  | 2020-10-08 22:35:38,303 websockets.protocol client - state = CONNECTING
alpaca-proxy_1  | 2020-10-08 22:35:38,306 websockets.protocol server - event = data_received(<128 bytes>)
alpaca-proxy_1  | 2020-10-08 22:35:38,306 websockets.protocol server < Frame(fin=True, opcode=1, data=b'{"action": "authenticate", "data": {"key_id": "123", "secret_key": "456"}}', rsv1=False, rsv2=False, rsv3=False)
alpaca-proxy_1  | < {'action': 'authenticate', 'data': {'key_id': '123', 'secret_key': '456'}}
alpaca-proxy_1  | 2020-10-08 22:35:38,307 websockets.protocol server > Frame(fin=True, opcode=1, data=b'{"data": {"status": "authorized"}, "stream": "authorization"}', rsv1=False, rsv2=False, rsv3=False)
alpaca-proxy_1  | 2020-10-08 22:35:38,322 websockets.protocol server - event = data_received(<51 bytes>)
alpaca-proxy_1  | 2020-10-08 22:35:38,323 websockets.protocol server < Frame(fin=True, opcode=1, data=b'{"action": "listen", "data": {"streams": ["alpacadatav1/Q.GOOG"]}}', rsv1=False, rsv2=False, rsv3=False)
alpaca-proxy_1  | < {'action': 'listen', 'data': {'streams': ['alpacadatav1/Q.GOOG']}}
alpaca-proxy_1  | 'NoneType' object has no attribute 'send'
alpaca-proxy_1  | Done
alpaca-proxy_1  | 2020-10-08 22:35:38,323 websockets.protocol server - state = CLOSING
alpaca-proxy_1  | 2020-10-08 22:35:38,323 websockets.protocol server > Frame(fin=True, opcode=8, data=b'\x03\xe8', rsv1=False, rsv2=False, rsv3=False)
alpaca-proxy_1  | 2020-10-08 22:35:38,334 websockets.protocol server - event = data_received(<8 bytes>)
alpaca-proxy_1  | 2020-10-08 22:35:38,334 websockets.protocol server < Frame(fin=True, opcode=8, data=b'\x03\xe8', rsv1=False, rsv2=False, rsv3=False)
alpaca-proxy_1  | 2020-10-08 22:35:38,334 websockets.protocol server x half-closing TCP connection
alpaca-proxy_1  | 2020-10-08 22:35:38,340 websockets.protocol server - event = eof_received()
alpaca-proxy_1  | 2020-10-08 22:35:38,341 websockets.protocol server - event = connection_lost(None)
alpaca-proxy_1  | 2020-10-08 22:35:38,341 websockets.protocol server - state = CLOSED
alpaca-proxy_1  | 2020-10-08 22:35:38,341 websockets.protocol server x code = 1000, reason = [no reason]
alpaca-proxy_1  | 2020-10-08 22:35:38,400 websockets.protocol client - event = connection_made(<asyncio.sslproto._SSLProtocolTransport object at 0x7f99412c8cf8>)
alpaca-proxy_1  | 2020-10-08 22:35:38,401 websockets.client client > GET /stream HTTP/1.1
alpaca-proxy_1  | 2020-10-08 22:35:38,401 websockets.client client > Headers([('Host', 'data.alpaca.markets'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'websoket_key'), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.6 websockets/8.1')])
alpaca-proxy_1  | 2020-10-08 22:35:38,445 websockets.protocol client - event = data_received(<188 bytes>)
alpaca-proxy_1  | 2020-10-08 22:35:38,446 websockets.client client < HTTP/1.1 101 Switching Protocols
alpaca-proxy_1  | 2020-10-08 22:35:38,446 websockets.client client < Headers([('Server', 'nginx/1.16.1'), ('Date', 'Thu, 08 Oct 2020 22:35:37 GMT'), ('Connection', 'upgrade'), ('Upgrade', 'websocket'), ('Sec-WebSocket-Accept', 'key=')])
alpaca-proxy_1  | 2020-10-08 22:35:38,446 websockets.protocol client - state = OPEN
alpaca-proxy_1  | 2020-10-08 22:35:38,446 websockets.protocol client > Frame(fin=True, opcode=1, data=b'{"action": "authenticate", "data": {"key_id": "123", "secret_key": "456"}}', rsv1=False, rsv2=False, rsv3=False)
alpaca-proxy_1  | 2020-10-08 22:35:38,558 websockets.protocol client - event = data_received(<83 bytes>)
alpaca-proxy_1  | 2020-10-08 22:35:38,559 websockets.protocol client < Frame(fin=True, opcode=1, data=b'{"stream":"authorization","data":{"action":"authenticate","status":"authorized"}}', rsv1=False, rsv2=False, rsv3=False)
alpaca-proxy_1  | 2020-10-08 22:35:38,559 root connected to: wss://data.alpaca.markets/stream
alpaca-proxy_1  | 2020-10-08 22:35:38,559 websockets.protocol client > Frame(fin=True, opcode=1, data=b'{"action": "listen", "data": {"streams": ["alpacadatav1/Q.AAPL"]}}', rsv1=False, rsv2=False, rsv3=False)
alpaca-proxy_1  | 2020-10-08 22:35:38,601 websockets.protocol client - event = data_received(<54 bytes>)
alpaca-proxy_1  | 2020-10-08 22:35:38,601 websockets.protocol client < Frame(fin=True, opcode=1, data=b'{"stream":"listening","data":{"streams":["Q.AAPL"]}}', rsv1=False, rsv2=False, rsv3=False)
alpaca-proxy_1  | 2020-10-08 22:35:45,582 websockets.protocol server - event = eof_received()
alpaca-proxy_1  | 2020-10-08 22:35:45,583 websockets.protocol server ! failing OPEN WebSocket connection with code 1006
alpaca-proxy_1  | 2020-10-08 22:35:45,583 websockets.protocol server - event = connection_lost(None)
alpaca-proxy_1  | 2020-10-08 22:35:45,583 websockets.protocol server - state = CLOSED
alpaca-proxy_1  | 2020-10-08 22:35:45,583 websockets.protocol server x code = 1006, reason = [no reason]
```

**Comment by observer-user** [comment]
Here is traceback from an exception
```
alpaca-proxy_1  | Traceback (most recent call last):
alpaca-proxy_1  |   File "main.py", line 160, in serve
alpaca-proxy_1  |     await conn.unsubscribe(previous_channels)
alpaca-proxy_1  |   File "/usr/local/lib/python3.6/site-packages/alpaca_trade_api/stream2.py", line 273, in unsubscribe
alpaca-proxy_1  |     await self.data_ws.unsubscribe(data_channels)
alpaca-proxy_1  |   File "/usr/local/lib/python3.6/site-packages/alpaca_trade_api/stream2.py", line 121, in unsubscribe
alpaca-proxy_1  |     await self._ws.send(json.dumps({
alpaca-proxy_1  | AttributeError: 'NoneType' object has no attribute 'send'
```

It happened inside `serve()` method

**Comment by shlomikushchi** [comment]
Hi, 
I just executed this example code and I don't get any errors.
also I run on windows 10 (with a slightly more updated packages we released yesterday but that shouldn't matter)
the polygon data stream works perfectly.
when using the alpaca data stream, it's a bit slim today. maybe the stream has some issues this morning.
but no errors

**Comment by observer-user** [comment]
I updated packages and using the following settings:
```
IS_BACKTEST = False
IS_LIVE = False
SYMBOL1 = 'AAPL'
SYMBOL2 = 'GOOG'
USE_POLYGON = False
```
And I still have the same error

**Comment by observer-user** [comment]
Finally, it's working only when I restart code sample without stopping the proxy. On initial run it throws the same error.

**Comment by observer-user** [comment]
@shlomikushchi, what is the maximum number of symbols I can use? I am trying to use 4 symbols, but proxy log only shows 2 first symbols

**Comment by shlomikushchi** [comment]
shouldn't be any limit. show me the logs

**Comment by observer-user** [comment]
@shlomikushchi, it looks like it was an issue due to as you mentioned

> when using the alpaca data stream, it's a bit slim today. maybe the stream has some issues this morning.
> but no errors

**Comment by KlausGlueckert** [comment]
I have the exact same issue! I just reviewed your logs. It also occurs, when I reboot the proxy, then the first time i launch the script i get the same error!!! @shlomikushchi
