### ISSUE TITLE
Can't Run Example -- Setting 'Paper' parameter to True doesn't connect to paper trading

### ISSUE THREAD

**Issue by Andrew5194** [alpacahq/alpaca-backtrader-api#16]
I'm not able to run the example provided at https://github.com/alpacahq/alpaca-backtrader-api. I want to connect the alpaca-backtrader-api to my Alpaca paper trading account but it seems to be trying to connect me to Polygon rather than IEX. I also specifically set the `paper` parameter to the AlpacaStore class as `True` and it doesn't seem to have an effect. Any thoughts?

P.S. I regenerated my keys :)

**Comment by Andrew5194** [comment]
![image](https://user-images.githubusercontent.com/20665775/64875998-351c8280-d61c-11e9-97c2-c0af391ab413.png)

**Comment by shinhwas** [comment]
I can't run too. Any update?

**Comment by shinhwas** [comment]
This is from bug. But it is already fixed. 
Please release new version!

**Comment by eliasluoma** [comment]
Hi, any updates regarding this. I have same issue.

Thanks in advance.

**Comment by mmahalwy** [comment]
same problem here. any updates?

**Comment by cole-seph** [comment]
same issue.

**Comment by SathishN** [comment]
+1

**Comment by TheHistoryMajor** [comment]
This is caused by leaving "historical = True". For paper trading, it needs to be "False," which effectively deactivates the "fromdate". Relevant code ----->

`data0 = DataFactory(
    dataname='AAPL',
    historical=False, #!!!
    fromdate=datetime(2015, 1, 1),
    timeframe=bt.TimeFrame.Minutes)
cerebro.adddata(data0)`

 @umitanuki details this in his Medium post on this topic, saying "All you need to do is to change the “historical=True” to False and set broker to Alpaca." (source: https://medium.com/automation-generation/introducing-alpaca-backtrader-integration-898d8cabffdc)

HOWEVER, doing this causes a second issue, resulting in error message:  

`Starting Portfolio Value: 10000.00
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/MyName/PycharmProjects/alpacatest/venv/lib/python3.7/site-packages/alpaca_backtrader_api/alpacastore.py", line 416, in _t_streaming_prices
    base_url=self.p.base_url)
  File "/Users/MyName/PycharmProjects/alpacatest/venv/lib/python3.7/site-packages/alpaca_backtrader_api/alpacastore.py", line 91, in __init__
    self.conn = tradeapi.StreamConn(api_key, api_secret, base_url)
  File "/Users/MyName/PycharmProjects/alpacatest/venv/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 27, in __init__
    self.loop = asyncio.get_event_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.
`

Alpaca + Backtrader are awesome. Really hoping we can get an example of an algorithm made in backtrader that can flipped "live" to Alpaca paper trading for testing. Fingers crossed.

**Comment by wstewarttennes** [comment]
I think this may have to do with polygon's depreciation of v1 aggregate.  I was getting the same error and was able to fix it by forking this and updating the polygon call on line 355 of alpacastore.py (and a few other lines) to the v2 aggregate api call.  Would be great if we could update this here so I can stay off my fork!

**Comment by shlomikushchi** [comment]
currently, alpaca_backtrader_api works with polygon as a datasource out of the box.
that means you need a live key to be able to access the polygon API

**Comment by shlomikushchi** [comment]
please check the version on pypi for the latest updates. 
this issue should be resolved. make sure you are using a funded alpaca account. 
let me know if there are any more issues with this.

**Comment by kr011** [comment]
@shlomikushchi I still have this issue. I have the latest package installed:

pip freeze | findstr alpaca-backtrader-api
alpaca-backtrader-api==0.7

I copy and pasted sma_crossover_strategy.py from samples folder. provided a live account ID and key (and actually changing "paper" to false for store) and still got this:

RuntimeError: There is no current event loop in thread 'Thread-11'.
